### ISSUE TITLE
Manually analyze CCN for BibEntry

### ISSUE THREAD

**Issue by henkejo** [DD2480-gr25/jabref#4]
BibEntry::getSourceField@139-252@src\main\java\org\jabref\model\entry\BibEntry.java

**Comment by pat672** [comment]
My count, based on the methodology "count all predicates and add 1":
```
13 ifs with 1 predicate = 13
1 if with 2 predicates = 2
2 ifs with 3 predicates = 6
1 if with 4 predicates = 4
1 if with 6 predicates = 6
1 if with 12 predicates = 12
1 if with 14 predicates = 14
1 if with 22 predicates = 22
+ 1
Result = 80
```

**Comment by emiros98** [comment]
My count, based on (decisions - endpoints + 2) (decisions = if, while, && and ||)

79 - 18 + 2 = 63

Worth noting: My number of decisions = Patryk's number of predicates

**Comment by emiros98** [comment]
The different results are caused by using different counting methods. This method did not contain any while loops, and the number of if, && and || anturally align with the number of predicates, so the main reason for the divergence is the fact that one count accounted for endpoints, while the other didn't.
